### ISSUE TITLE
text decoration is overbodig. 

### ISSUE THREAD

**Issue by mcphendriks** [ArexanK/Oba-server-side-rendering#10]
https://github.com/ArexanK/server-side-rendering/blob/d9789c845ac228333d97d6d2c2eb531b158fd9e6/public/styles/new.css#L279

Je gebruikt geen links <a> in je sections
(https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration)

**Comment by ArexanK** [comment]
klopt ik ga het weghalen.
